In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kashmir_temp=73
kashmir_rain=67
kashmir_humid=43

In [3]:
kashmir_yields_apple=kashmir_temp*w1 + kashmir_rain*w2 + kashmir_humid*w3
print(kashmir_yields_apple)

56.8


In [4]:
kashmir=[73,67,43]
himachal=[91,88,64]
nepal=[87,134,58]
russia=[102,43,37]
dubai=[69,96,70]

weights=[w1,w2,w3]

In [5]:
for items in zip(kashmir,weights):
    print(items)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [6]:
def crop_yield(region,weights):
    result=0
    for x,w in zip(region,weights):
        result+=x*w
    return result


In [7]:
print(crop_yield(kashmir,weights))
print(crop_yield(himachal,weights))
print(crop_yield(nepal,weights))
print(crop_yield(russia,weights))
print(crop_yield(dubai,weights))

56.8
76.9
81.9
57.699999999999996
74.9


# NUMPY
### Numerical Python
#### 

In [8]:
#pip install numpy
import numpy as np

In [9]:
kashmir=np.array([73,67,43])
weights=np.array(weights)

In [10]:
print(type(kashmir))
print(type(weights))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
print(kashmir[0])
print(weights[1])

73
0.2


In [12]:
np.dot(kashmir,weights)

np.float64(56.8)

In [13]:
arr=kashmir*weights
print(arr)
arr.sum()

[21.9 13.4 21.5]


np.float64(56.8)

In [14]:
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))

x=np.array(arr1)
y=np.array(arr2)

In [15]:
%%time
result=0
for x,y in zip(arr1,arr2):
    result+=x*y
result

CPU times: total: 375 ms
Wall time: 354 ms


833332333333500000

In [16]:
%%time
np.dot(x,y)

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(1999997000001)

#### Multi Dimensional Array

In [17]:
climate_data=np.array([[73,67,43],
                      [91,88,64],
                      [87,134,58],
                      [102,43,37],
                      [69,96,70]])

In [18]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [19]:
print(type(climate_data))
print(climate_data.shape)

<class 'numpy.ndarray'>
(5, 3)


In [20]:
arr3=np.array([
    [[11,12,13],
    [13,14,15]],
    [[15,16,17],
    [17,18,19.5]]
])
print(arr3.ndim)
arr3


3


array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [21]:
print(type(arr3))
print(arr3.shape)

<class 'numpy.ndarray'>
(2, 2, 3)


In [22]:
print(climate_data.dtype)
print(arr3.dtype)

int64
float64


#### Matrix Multpication

In [23]:
np.matmul(climate_data,weights)


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [24]:
climate_data @ weights
np.dot(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [25]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return 

#### reading csv data 

In [26]:
climate_data=np.genfromtxt('weather_data.txt', delimiter=',' , skip_header=1)

In [27]:
climate_data

array([[10.68300109, 36.6       ,  8.23354025],
       [ 8.73413978, 35.1       , 27.71516126],
       [11.63243631, 35.6       , 28.73295129],
       [-8.6289759 , 32.9       , 26.36730267],
       [39.80821297, 35.5       , 29.89862167],
       [27.34105487, 47.8       , 27.47389608],
       [ 1.88188337, 60.3       ,  1.07311178],
       [-6.89476554, 51.4       , 16.84833687],
       [ 0.96354489, 29.7       ,  7.98902397],
       [-1.60708804, 32.4       , 25.64728207],
       [35.14555907, 46.9       , 25.43031002],
       [15.81676357, 43.4       , 16.75213221],
       [32.01689761, 34.2       ,  3.05019639],
       [38.64126926, 33.9       , 20.77926401],
       [39.66677192, 40.        ,  6.4794921 ],
       [28.29011469, 50.2       , 14.06676464],
       [16.3497895 , 51.2       ,  6.59703904],
       [26.78681109, 55.9       , 22.9800953 ],
       [35.17954764, 31.1       ,  4.50786271],
       [14.60581923, 23.7       , 29.4318902 ],
       [33.02335072, 39.3       , 16.733

In [28]:
climate_data.shape

(100, 3)

In [29]:
weights=np.array([0.3,0.2,0.5])

In [30]:
yields=climate_data @ weights
yields

array([14.64167045, 23.49782256, 24.97620654, 17.17495857, 33.99177473,
       31.4992645 , 13.1611209 , 16.63573877, 10.22357545, 18.82151462,
       32.63882273, 21.80109518, 17.97016748, 28.76201278, 23.13977762,
       25.56041673, 18.44345637, 30.70609098, 19.02779565, 23.83769087,
       26.13366766, 11.56338889, 25.98988128, 22.60426881, 18.0261364 ,
       10.13541041, 27.64741119, 12.19138912, 10.76114132,  8.67582513,
       22.86109614, 18.02350887, 17.17341926, 21.24546121, 23.71814494,
       22.98036176, 22.13960028, 13.38024576,  4.73188072, 19.87101881,
       19.1671684 , 28.75467011, 15.84715952, 13.78068631, 33.04061705,
       18.77042758, 28.5996695 , 21.34210359, 19.41422024, 27.79592218,
        6.63483627, 19.38510561, 26.57758163, 17.30711697, 16.1171522 ,
       26.53664673, 30.69008431, 24.76099848, 32.74321272, 22.58754358,
       21.9006802 , 21.2128584 , 27.22319928,  8.29599351, 24.65433277,
       35.29569658, 24.35416656, 19.02002086, 32.73940454, 21.67

In [31]:
yields.shape

(100,)

In [32]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...), 
        axis=0, 
        out=None, 
        dtype=None, 
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded

In [33]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)
[[5 6]
 [7 8]]
(2, 2)


In [34]:
np.concatenate((b,a),axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [35]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6,9],
            [7,8,10]])

In [36]:
c=np.concatenate((a,b), axis=1)
c.reshape(5,2)

array([[ 1,  2],
       [ 5,  6],
       [ 9,  3],
       [ 4,  7],
       [ 8, 10]])

In [37]:
print(yields.shape)
yields.reshape(100,1)

(100,)


array([[14.64167045],
       [23.49782256],
       [24.97620654],
       [17.17495857],
       [33.99177473],
       [31.4992645 ],
       [13.1611209 ],
       [16.63573877],
       [10.22357545],
       [18.82151462],
       [32.63882273],
       [21.80109518],
       [17.97016748],
       [28.76201278],
       [23.13977762],
       [25.56041673],
       [18.44345637],
       [30.70609098],
       [19.02779565],
       [23.83769087],
       [26.13366766],
       [11.56338889],
       [25.98988128],
       [22.60426881],
       [18.0261364 ],
       [10.13541041],
       [27.64741119],
       [12.19138912],
       [10.76114132],
       [ 8.67582513],
       [22.86109614],
       [18.02350887],
       [17.17341926],
       [21.24546121],
       [23.71814494],
       [22.98036176],
       [22.13960028],
       [13.38024576],
       [ 4.73188072],
       [19.87101881],
       [19.1671684 ],
       [28.75467011],
       [15.84715952],
       [13.78068631],
       [33.04061705],
       [18

In [38]:
result=np.concatenate((climate_data,yields.reshape(100,1)), axis=1)
result

array([[10.68300109, 36.6       ,  8.23354025, 14.64167045],
       [ 8.73413978, 35.1       , 27.71516126, 23.49782256],
       [11.63243631, 35.6       , 28.73295129, 24.97620654],
       [-8.6289759 , 32.9       , 26.36730267, 17.17495857],
       [39.80821297, 35.5       , 29.89862167, 33.99177473],
       [27.34105487, 47.8       , 27.47389608, 31.4992645 ],
       [ 1.88188337, 60.3       ,  1.07311178, 13.1611209 ],
       [-6.89476554, 51.4       , 16.84833687, 16.63573877],
       [ 0.96354489, 29.7       ,  7.98902397, 10.22357545],
       [-1.60708804, 32.4       , 25.64728207, 18.82151462],
       [35.14555907, 46.9       , 25.43031002, 32.63882273],
       [15.81676357, 43.4       , 16.75213221, 21.80109518],
       [32.01689761, 34.2       ,  3.05019639, 17.97016748],
       [38.64126926, 33.9       , 20.77926401, 28.76201278],
       [39.66677192, 40.        ,  6.4794921 , 23.13977762],
       [28.29011469, 50.2       , 14.06676464, 25.56041673],
       [16.3497895 , 51.

In [39]:
np.savetxt('Yields.txt', result,
           fmt='%.2f',
           header="temerature,rainfall,humidity,yield",
           delimiter=',',
           comments='')

#### Arithmetic operations 

In [60]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr2=np.array([[10,11,12,13],
               [14,15,16,17],
               [18,19,20,21]])

In [41]:
arr+1    #Adding Scalar value

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [61]:
arr2-arr

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [43]:
arr-5

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [44]:
arr**2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [45]:
arr/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [46]:
arr%3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]])

#### Arithmetic Broadcasting 
##### allows arithmetic operations between two numpy arrays having different number of dimensions, but compatible shapes.

In [54]:
arr1=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print(arr2.shape)
#size can be used to find number of elements
print(arr.size)                                        

(3, 4)
12


In [55]:
arr3=np.array([4,5,7,8])
arr3.shape

(4,)

In [65]:
arr1+arr3

array([[ 5,  7, 10, 12],
       [ 9, 11, 14, 16],
       [13, 15, 18, 20]])

In [ ]:
#Example 3 D array

In [ ]:
new1=np.array([[1,2,3],[3,4,5]])
new2=np.array([[2,2,3],[1,2,5]])

In [ ]:
new1==new2

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
new1!=new2

array([[ True, False, False],
       [ True,  True, False]])

In [ ]:
new1>=new2

array([[False,  True,  True],
       [ True,  True,  True]])

In [ ]:
new1<=new2

array([[ True,  True,  True],
       [False, False,  True]])

In [ ]:
new1<new2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
np.sum(new1==new2)

np.int64(3)

In [70]:
#Universal Functions
arr=np.array([1,2,3,4,5,6])
print(arr)

#Square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#log 
print(np.log(arr))

[1 2 3 4 5 6]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
#Statistical Concepts 
#Standard deviation : have mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

#Mean and Standard Deviation
mean=np.mean(data)
std_dev=np.std(data)
print(mean)
print(std_dev)
#rint(np.var(data))

#normalize
normalized_data=(data-mean)/std_dev
print("Normalized data : ",normalized_data)
print(np.mean(normalized_data))
print(np.std(normalized_data))

3.0
1.4142135623730951
2.0
Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [80]:

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(arr))          #mean
print(np.median(arr))        #median
print(np.std(arr))          #standard deviation
print(np.var(arr))          #variance

5.5
5.5
2.8722813232690143
8.25


In [86]:
#logical operations
print(arr[arr>5])
arr[(arr>5) | (arr>9)]

[ 6  7  8  9 10]


array([ 6,  7,  8,  9, 10])

In [115]:
a=np.datetime64('today','D')
a

np.datetime64('2026-03-18')

In [117]:
tom=a-np.timedelta64(3,'D')
tom

np.datetime64('2026-03-15')

In [126]:
np.zeros((12,3), dtype=int).reshape(3,2,6)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [134]:
a=np.ones((4,4), dtype=int)
a[0::3]=0
a[:,::3]=0
a

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [139]:
np.full((3,3), 66).reshape(9,)

array([66, 66, 66, 66, 66, 66, 66, 66, 66])

In [147]:
a=np.arange(1,100,5)
len(a)
a.reshape(4,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [151]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.random.seed(56)
np.random.randn(3,3).sum()/np.random.randn(3,3).size

np.float64(-0.18765122508791604)

In [178]:
np.linspace(1,100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [183]:
a=np.arange(1,10)
print(a)
a.cumprod()

[1 2 3 4 5 6 7 8 9]


array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])